# Generated by Django 6.0.2 on 2026-05-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='original_request',
            field=models.JSONField(default=dict),
        ),
    ]
