# Generated by Django 6.0.2 on 2026-05-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_recipe_original_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='creator_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
